23832884  SearchBooksByAuthor
anna-bc/hall-of-books-backend pull request #21
Opened 2023-03-27 10:18 UTC by tinkabel85

2023-03-27 10:41 UTC, naomiinanna approved these changes

2023-03-27 11:28 UTC, naomiinanna approved these changes

2023-03-28 08:30 UTC, anna-bc requested changes

2023-03-28 08:45 UTC, tinkabel85 commented on config/routes.yaml
> +    controller: App\Controller\BookController::searchBooksByAuthor
done!

2023-03-28 09:46 UTC, naomiinanna approved these changes

2023-03-28 09:50 UTC, anna-bc approved these changes

2023-03-28 10:06 UTC, merged